version: '1.0'
name: BuildPipeline
displayName: BuildPipeline
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - 跑不通_master
variables:
  global:
    - ACTION
    - GIT_EMAIL
    - GIT_PASS
    - GIT_USER
stages:
  - name: stage-7c5194ef
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行构建脚本'
          - bash build.sh ${ACTION}
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
