version: '1.0'
name: deploy-demo-cs
displayName: deploy-demo-cs
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
    paths:
      precise:
        - demo-cs.html
stages:
  - name: stage-51da6b56
    displayName: 拷贝
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: copy_demo-cs
        displayName: 拷贝demo-cs
        nodeVersion: 14.16.0
        commands:
          - '# 删除远程仓库'
          - git remote rm origin
          - ''
          - '# 新增仓库设置'
          - git remote add origin https://glnp:1qaz1234.gglnp@gitee.com/goeasy-io/demo-customer-service.git
          - git config --global user.email "guilin@goeasy.io"
          - ''
          - '# 强制切换分支'
          - git fetch
          - git checkout -f deploy
          - ''
          - '# 删除老的demo-cs.html'
          - rm -f demo-cs.html
          - ''
          - '# 复制master文件夹到此'
          - git restore -s master -- demo-cs.html
          - ''
          - '# 执行推送'
          - git add demo-cs.html
          - git commit -m 'Adding demo-cs.html directory from master branch.'
          - git push
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
