version: '1.0'
name: TestBranch
displayName: TestBranch
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - 跑不通_master
variables:
  global:
    - GIT_EMAIL
    - GIT_PASS
    - GIT_USER
    - ACTION
stages:
  - name: stage-8b34cfe4
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - ''
          - echo $ACTION
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
