version: '1.0'
name: test
displayName: test
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - 跑不通_master
variables:
  latest_version: 1.0.9
stages:
  - name: stage-88f9827c
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - echo "latest_version${latest_version}"
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
