version: '1.0'
name: test
displayName: test
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - 跑不通_master
variables:
  latest_version: 1.0.9
stages:
  - name: stage-88f9827c
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - echo 'start latest_version:${latest_version}'
          - ''
          - echo '${test_version[0]}=1.0.8' >> GITEE_PARAMS
          - ''
          - echo '${test_version[1]}=1.0.7' >> GITEE_PARAMS
          - ''
          - echo '${test_version[2]}=1.0.6' >> GITEE_PARAMS
          - ''
          - echo "end latest_version:${latest_version}"
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
